# Generated by Django 3.1.1 on 2020-09-30 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=30, null=True)),
                ('minor', models.CharField(max_length=30, null=True)),
                ('github', models.URLField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.profile'),
        ),
    ]
