# Generated by Django 3.1.1 on 2020-10-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_room',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='textbook',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
