# Generated by Django 3.1.2 on 2020-10-13 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0002_auto_20201012_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='created_in_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country1', to='film_app.country'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(related_name='director', to='film_app.Director'),
        ),
    ]
