# Generated by Django 3.1.1 on 2020-10-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20201011_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
